import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/components/Header";
import { Noto_Serif_JP } from "next/font/google";
import { Footer } from "@/app/components/Footer";
import {MobileHeader} from "@/app/components/MobileHeader";
import {MobileFooter} from "@/app/components/MobileFooter";

const inter = Inter({ subsets: ["latin"] });
const notoserifjp = Noto_Serif_JP({
  weight: ['200', '300', '400', '500', '600', '700', '900'],
  style : "normal",
  subsets: ['latin']
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export async function generateStaticParams() {
  return [{lang: 'en'}, {lang: 'jp'}, {lang: 'cn'}]
}

export default function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={params.lang}>
      <body className={`${inter.className} ${notoserifjp.className}`}>
        <Header lang={params.lang}/>
        <MobileHeader lang={params.lang}/>
        {children}
        <MobileFooter lang={params.lang}/>
        <Footer/>
      </body>
    </html>
  );
}
